version: '3.1'

networks:
  ship_sticks_dev_challenge:
    external: true

services:
  db:
    image: mongo:4.2
    container_name: ship_sticks_dev_challenge-db
    networks:
      - ship_sticks_dev_challenge
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: A9XO#cy!!7cG
      MONGO_INITDB_DATABASE: ship_sticks_dev_challenge_development
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  api:
    build: ./backend
    container_name: ship_sticks_dev_challenge-api
    networks:
      - ship_sticks_dev_challenge
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/ship_sticks_dev_challenge
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    image: httpd:2.4
    container_name: ship_sticks_dev_challenge-web
    networks:
      - ship_sticks_dev_challenge
    ports:
      - "8080:80"
    volumes:
      - ./frontend/:/usr/local/apache2/htdocs/
    depends_on:
      - api

volumes:
  db-data:
